name: Run Selenium Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and start Selenium Grid
        run: |
          docker compose -f docker-compose.yml up --build -d

       - name: Run Maven tests in app container
        run: docker compose -f docker-compose.yml run app

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: reports/

      - name: Shut down and clean up
        run: docker-compose -f docker-compose.yml down --volumes
